### PR TITLE
chore(patch): enable pwritev() [sc-3462]

### PR DESCRIPTION
**Pull request by dimlio**
Make LMDB use pwritev() syscall.

This can improve performance by reducing the number of syscalls (i.e. user <-> kernel transitions).

Fixes Shortcut story [[sc-2898](https://app.shortcut.com/ordo-one/story/2898)]

Corresponding PR to upstream: https://github.com/apple/swift-lmdb/pull/3

### CODE REVIEW

**Comment by hassila** [comment]
You will want to the the upstream PR here, to the real upstream https://git.openldap.org/openldap/openldap/tree/mdb.master I think, but interesting!

**Comment by hassila** [comment]
Oh, I just saw its a setting?!

**Review by freef4ll — APPROVED** [review]

**Review by ser-0xff — APPROVED** [review]

**Comment by hassila** [comment]
Can I suggest to run the DocC test suite for this, similar to what I did in https://github.com/apple/swift-lmdb/pull/2

It actually caught issues, worth doing it on this one too? It's quite extensive tests.

**Comment by hassila** [comment]
(also, if you have any performance numbers to share with/without pwrite in LMDB it would be interesting also)

**Comment by dimlio** [comment]
> Can I suggest to run the DocC test suite for this, similar to what I did in [apple#2](https://github.com/apple/swift-lmdb/pull/2)
>
> It actually caught issues, worth doing it on this one too? It's quite extensive tests.



Successfully run `swift-docc` test suite against LMDB with `pwritev()` enabled.

But, got the following build warning:

```
/Users/sbn/GitHub/swift-docc/Packages/swift-lmdb/Sources/CLMDB/mdb.c:3791:12: warning: 'pwritev' is only available on macOS 11.0 or newer [-Wunguarded-availability-new]
                                wres = pwritev(fd, iov, n, wpos);
                                       ^~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/uio.h:104:9: note: 'pwritev' has been marked as being introduced in macOS 11.0 here, but the deployment target is macOS 10.13.0
ssize_t pwritev(int, const struct iovec *, int, off_t) __DARWIN_NOCANCEL(pwritev) __API_AVAILABLE(macos(11.0), ios(14.0), watchos(7.0), tvos(14.0));
        ^
/Users/sbn/GitHub/swift-docc/Packages/swift-lmdb/Sources/CLMDB/mdb.c:3791:12: note: enclose 'pwritev' in a __builtin_available check to silence this warning
                                wres = pwritev(fd, iov, n, wpos);
                                       ^~~~~~~
```

And indeed they have `.macOS(.v10_15)` as a deployment target.
So it seems they won't take the change...
 [](edited-with-Axolo)

**Comment by hassila** [comment]
I guess it depends on when they roll over from v10 to v11, let's see what they say - worth mentioning the issue perhaps. Did you see any real performance improvement with it? It might be a carrot to move it forward perhaps.

**Review by hassila — APPROVED** [review]
It looks like this is mostly useful when writing multiple transactions in a batch - as it happens that's a very important use case for us, so let's do this locally in our fork and repoint any internal packages to it as needed. Would be very interesting to see the batched transaction benchmark with/without this flag @dimlio - if easy to run.

**Comment by dimlio** [comment]
> It looks like this is mostly useful when writing multiple transactions in a batch - as it happens that's a very important use case for us, so let's do this locally in our fork and repoint any internal packages to it as needed. Would be very interesting to see the batched transaction benchmark with/without this flag @dimlio - if easy to run.

Yes, it was my idea too.
But it seems this not only doesn't provide any improvements, but even makes it slightly worse -- number of syscalls is increased.
Results for writing to DB in batches of 1024 records:

With `pwritev()` enabled:

```
{
  "readBytesLogical" : 448,
  "readBytesPhysical" : 0,
  "readSyscalls" : 2,
  "wallClock" : 14_989_376_350,
  "writeBytesLogical" : 770214392,
  "writeBytesPhysical" : 292044800,
  "writeSyscalls" : 22631
}
```

Without `pwritev()`:

```
"readBytesLogical" : 448,
  "readBytesPhysical" : 0,
  "readSyscalls" : 2,
  "wallClock" : 14_913_678_246,
  "writeBytesLogical" : 770230776,
  "writeBytesPhysical" : 292139008,
  "writeSyscalls" : 22501
```
 [](edited-with-Axolo)

**Comment by hassila** [comment]
> > It looks like this is mostly useful when writing multiple transactions in a batch - as it happens that's a very important use case for us, so let's do this locally in our fork and repoint any internal packages to it as needed. Would be very interesting to see the batched transaction benchmark with/without this flag @dimlio - if easy to run.
> 
> 
> 
> Yes, it was my idea too.
> 
> But it seems this not only doesn't provide any improvements, but even makes it slightly worse -- number of syscalls is increased.
> 
> Results for writing to DB in batches of 1024 records:
> 
> 
> 
> With `pwritev()` enabled:
> 
> 
> 
> ```
> 
> {
> 
>   "readBytesLogical" : 448,
> 
>   "readBytesPhysical" : 0,
> 
>   "readSyscalls" : 2,
> 
>   "wallClock" : 14_989_376_350,
> 
>   "writeBytesLogical" : 770214392,
> 
>   "writeBytesPhysical" : 292044800,
> 
>   "writeSyscalls" : 22631
> 
> }
> 
> ```
> 
> 
> 
> Without `pwritev()`:
> 
> 
> 
> ```
> 
> "readBytesLogical" : 448,
> 
>   "readBytesPhysical" : 0,
> 
>   "readSyscalls" : 2,
> 
>   "wallClock" : 14_913_678_246,
> 
>   "writeBytesLogical" : 770230776,
> 
>   "writeBytesPhysical" : 292139008,
> 
>   "writeSyscalls" : 22501
> 
> ```
> 
>  [](edited-with-Axolo)

Haha, wow :-) 

Quite unexpected- good you tested, thanks - probably not worthwhile to merge then - would close the upstream pr until we see provable improvements.

**Comment by dimlio** [comment]
Let's close for now.

**Pull request closed without merging**
